#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          SCRIPTNAME
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Python INSERT.SOMETHING.MEANINGFUL
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=SCRIPTNAME
DESC="Python service starter"

cmd="/../../scriptname.py"

case "$1" in
start)
sudo -u USER -i screen -dmS SCRIPTNAME.start python $cmd
echo "Service started"
;;
stop)
sudo -u openhabian -i screen -S SCRIPTNAME.start -X quit
echo "Process killed"
;;
restart)
sudo -u USER -i screen -S SCRIPTNAME.start -X quit
echo "Killed" &
sudo -u USER -i screen -dmS SCRIPTNAME.start python $cmd
echo "Service restarted"
;;
esac

exit 0
